// src/portability/importer.ts
//
// Stage 13 PR10 (spec § 6.7): the import side of the
// portability contract. `importMemoryExport(root, ...)`
// reads a previously-exported scope (the manifest +
// per-topic files) and replays the entries into a live
// `MemoryService`. The import is the inverse of the
// export; it is the only supported way to populate a
// fresh DB from an external data source.
//
// Conflict policy (spec § 6.7):
//   - keep:      skip entries that already exist in the
//                live store; new entries are imported.
//   - replace:   overwrite the live entry with the
//                imported one. The imported entry must
//                carry a `revision` that matches the
//                live `revision` (CAS-style safety), or
//                the import refuses.
//   - merge:     combine tags + body, preserve the
//                higher importance / confidence.
//   - fail:      any conflict aborts the whole import
//                without writing anything.
//
// Stage 16 v1.1.1 PR-4 (issue #13): every import goes
// through a preflight phase that reuses the live write
// validators. The preflight runs BEFORE any mutation
// and refuses the entire plan if any entry fails:
//   - schema / enum validation (validateRememberInput);
//   - secret detection (detectSecrets on body);
//   - sensitivity policy (`restricted` may not leave
//     the source DB without an explicit override);
//   - project identity (strict_existing mode —
//     `project_path` resolves, `project_id`-only
//     rejects unless the identity is already
//     registered);
//   - aggregate batch budget (sum of the per-entry
//     sizes must fit the target budget);
//   - id / revision conflict policy (CAS check).
//
// Stage 16 v1.1.1 PR-4 (issue #13): every imported
// entry's `trust_level` is forced to `"imported"`. A
// re-hashed but tampered bundle that carries
// `user_confirmed` is downgraded on apply. A stronger
// trust decision can only be restored by an explicit
// `restore_trust` flag (the trusted-bundle mechanism).
//
// Stage 16 v1.1.1 PR-4 (issue #13): every import
// generates a stable `import_batch_id` and a
// `bundle_hash`. Both are recorded on every
// `audit_events` row generated by the apply, so a
// later reviewer can trace the row back to the exact
// bundle that produced it.
//
// Stage 16 v1.1.1 PR-4 (issue #13): two history modes.
//   - `snapshot` (default) imports the current entry
//     fields only. The live row starts at revision 1
//     with a single `created` audit event stamped by
//     the import batch.
//   - `full_history` imports the entries PLUS the
//     attached `memory_revisions` rows and the
//     related `audit_events`. The revision ordering
//     and the audit chain are preserved end-to-end.
//     Only `restore_trust` + `full_history` together
//     can re-claim a non-imported `trust_level`.
//
// Dry-run mode returns the plan (the entries that
// would be inserted / replaced / merged) without
// mutating the live store. This is the safe default
// for the CLI.

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  type MemoryEntry,
  type MemoryScope,
  type Result
} from "../domain.js";
import { err, ok } from "../domain.js";
import { detectSecrets } from "../secret-detector.js";
import { validateRememberInput } from "../write-validator.js";
import type { MemoryService } from "../memory-service.js";
import { readManifest, verifyManifest, MANIFEST_FILENAME, type Manifest } from "./manifest.js";
import {
  computeBundleHash,
  detectBundleGeneration,
  newImportBatchId,
  normaliseBundle,
  type BundleGeneration,
  type NormalisedBundle
} from "./migration-adapter.js";

export type ConflictPolicy = "keep" | "replace" | "merge" | "fail";

export type ImportHistoryMode = "snapshot" | "full_history";

export type ImportSensitivityPolicy = "normal" | "private" | "restricted";

/**
 * Preflight errors. A preflight failure is a
 * contract-level rejection of the bundle, distinct
 * from a per-entry write error. The preflight phase
 * returns a structured `{ ok: false, error, ... }`
 * so the CLI can print the failing entry id +
 * reason without leaking the entry body. The
 * failing entry id (if any) is in `details.entry_id`.
 */
export type PreflightError =
  | "invalid_schema"
  | "invalid_state"
  | "secret_detected"
  | "sensitivity_denied"
  | "identity_conflict"
  | "aggregate_budget"
  | "revision_drift"
  | "bundle_garbled"
  | "unauthorized";

export type PreflightResult = Result<
  {
    bundle: NormalisedBundle;
    import_batch_id: string;
  },
  PreflightError
>;

export type ImportPlan = {
  manifest: Manifest;
  scope: MemoryScope;
  project_id?: string;
  /** Bundle generation after the migration adapter. */
  generation: BundleGeneration;
  /** Stable bundle hash (sha256 of the normalised bundle). */
  bundle_hash: string;
  /** UUID identifying this import run. */
  import_batch_id: string;
  /** `snapshot` or `full_history`. */
  history_mode: ImportHistoryMode;
  /** Entries that will be inserted (no existing id). */
  inserts: MemoryEntry[];
  /** Entries that will be replaced (existing id, conflict policy != keep). */
  replacements: { imported: MemoryEntry; existing: MemoryEntry }[];
  /** Entries that will be skipped under `keep`. */
  skipped: MemoryEntry[];
  /** Per-entry status, in import order. */
  decisions: Array<
    | { kind: "insert"; memory_id: string }
    | { kind: "replace"; memory_id: string }
    | { kind: "merge"; memory_id: string }
    | { kind: "skip"; memory_id: string; reason: string }
  >;
};

export type ImportOptions = {
  conflict: ConflictPolicy;
  dry_run: boolean;
  actor: string;
  /**
   * When true (the default), abort on a manifest
   * hash mismatch. Stage 15 PR-M0-3 (issue #4, spec
   * § 6.7) flips the default to true — the v1
   * contract made the verification opt-in, which
   * meant an entry could be silently dropped from
   * the export without the import noticing.
   */
  require_clean_manifest?: boolean;
  /**
   * Stage 16 v1.1.1 PR-4 (issue #13). `snapshot`
   * (default) imports the current entry fields
   * only. `full_history` also restores the
   * `memory_revisions` and `audit_events` chain.
   */
  history_mode?: ImportHistoryMode;
  /**
   * Stage 16 v1.1.1 PR-4 (issue #13). The live
   * sensitivity policy. `restricted` entries may
   * not leave the source DB unless the caller
   * passes `allow_restricted: true`.
   */
  allow_restricted?: boolean;
  /**
   * Stage 16 v1.1.1 PR-4 (issue #13). When true,
   * a `full_history` import is allowed to restore
   * a `user_confirmed` trust tier from the bundle.
   * Default `false`. The trusted-bundle mechanism
   * in this release is the explicit
   * `--restore-trust` CLI flag; remote signing
   * infrastructure is explicitly a non-goal.
   */
  restore_trust?: boolean;
};

export type ImportResult = {
  applied: boolean;
  plan: ImportPlan;
  duration_ms: number;
  /** Ids of the entries that were actually written. */
  applied_ids: string[];
  /** The import batch id (also on the plan). */
  import_batch_id: string;
};

/**
 * Read the export directory's MANIFEST.json and the
 * per-topic files into a flat list of entries. The
 * caller passes the scope + project_id that the export
 * was produced for; the importer does not infer it
 * from the manifest alone (project_id is a path
 * segment, the manifest only records the scope label).
 */
export function readImportBundle(exportScopeDir: string, scope: MemoryScope, project_id?: string): Manifest {
  if (!existsSync(exportScopeDir)) {
    throw new Error(`export directory not found: ${exportScopeDir}`);
  }
  if (!existsSync(join(exportScopeDir, MANIFEST_FILENAME))) {
    // Stage 16 v1.1.1 PR-4 (issue #13): the v1
    // path threw `manifest not found` for v0
    // bundles. The migration adapter now
    // synthesises a v1 manifest for v0 bundles,
    // so the caller should not hit this error in
    // normal use; the throw stays for a corrupt
    // export directory that has no manifest and
    // no `topics/` subdir.
    throw new Error(
      `export directory has no MANIFEST.json: ${exportScopeDir} (try the migration-adapter to read pre-v1 bundles)`
    );
  }
  const manifest = readManifest(exportScopeDir);
  if (manifest.scope !== expectedScopeLabel(scope, project_id)) {
    throw new Error(
      `manifest scope mismatch: manifest=${manifest.scope} expected=${expectedScopeLabel(scope, project_id)}`
    );
  }
  return manifest;
}

function expectedScopeLabel(scope: MemoryScope, project_id?: string): string {
  return scope === "project" ? `project/${project_id ?? "unknown-project"}` : "global";
}

export type ImportFormat = "json";

function extensionFor(format: ImportFormat): string {
  // JSON-only now (Stage 15 PR-M0-3, issue #4).
  return format;
}

function parseEntries(body: string, format: "markdown" | "json"): MemoryEntry[] {
  if (format === "markdown") {
    throw new Error("importing from markdown is not supported; use the json export");
  }
  if (format !== "json") {
    throw new Error(`unsupported import format: ${format} (only "json" is supported)`);
  }
  const parsed = JSON.parse(body) as { entries: MemoryEntry[] };
  return parsed.entries ?? [];
}

/**
 * Stage 16 v1.1.1 PR-4 (issue #13): the preflight
 * phase. Runs every entry through the live write
 * validators, plus the project identity check, the
 * sensitivity policy, the aggregate budget check, and
 * the id / revision CAS check. The preflight returns
 * either `{ ok: true, bundle, import_batch_id }` or
 * `{ ok: false, error, message, entry_id }`. A
 * preflight failure aborts the import; nothing is
 * written to the live store.
 *
 * The preflight also generates the `import_batch_id`
 * and computes the `bundle_hash`. Both are returned
 * so the apply phase can stamp them on every audit
 * event.
 */
export function preflightImport(
  service: MemoryService,
  exportScopeDir: string,
  scope: MemoryScope,
  project_id: string | undefined,
  format: ImportFormat,
  options: ImportOptions
): PreflightResult {
  // Bundle normalisation (covers v0 / v1 / v2
  // bundles). The adapter is a no-op for v2
  // bundles.
  let bundle: NormalisedBundle;
  try {
    bundle = normaliseBundle(exportScopeDir, format);
  } catch (e) {
    return err("bundle_garbled", e instanceof Error ? e.message : String(e), {
      reason: e instanceof Error ? e.message : String(e)
    });
  }
  // Re-verify the manifest. The adapter does not
  // touch on-disk bytes for v1 / v2 bundles, so a
  // post-normalisation verify still catches a
  // tampered file.
  if (options.require_clean_manifest !== false) {
    if (existsSync(join(exportScopeDir, MANIFEST_FILENAME))) {
      const manifestOnDisk = readManifest(exportScopeDir);
      const mismatches = verifyManifest(exportScopeDir, manifestOnDisk);
      if (mismatches.length > 0) {
        return err(
          "bundle_garbled",
          `manifest hash mismatch: ${mismatches.length} file(s) do not match the manifest (${mismatches.join(", ")})`,
          { mismatches }
        );
      }
    }
  }
  // For each entry: schema / secret / sensitivity
  // / id / revision. The live project identity
  // resolver runs in `strict_existing` mode so a
  // `project_id`-only input that lacks a registered
  // identity is rejected at the preflight stage
  // (rather than silently creating a new identity
  // from the bundle).
  for (const entry of bundle.entries) {
    // 1. schema / enum / secret. The validator may
    // reject the entry with `invalid_schema` OR
    // `secret_detected`; the preflight surfaces the
    // original code so the CLI can branch on it
    // without re-parsing the message.
    const validated = validateRememberInput(entryToRememberInput(entry));
    if (!validated.ok) {
      const preflightError: PreflightError = validated.error;
      return err(
        preflightError,
        `entry ${entry.id} failed ${validated.error}: ${validated.message}`,
        { entry_id: entry.id, ...(validated.details ?? {}) }
      );
    }
    // 2. secret detection (the validator already
    // ran this on body + title + tags; we re-run
    //    on body so the preflight error names the
    //    field explicitly).
    const findings = detectSecrets(entry.body, "body");
    if (findings.length > 0) {
      return err(
        "secret_detected",
        `entry ${entry.id} contains a potential secret (categories: ${findings.map((f) => f.category).join(", ")})`,
        { entry_id: entry.id }
      );
    }
    // 3. sensitivity policy.
    if (entry.sensitivity === "restricted" && options.allow_restricted !== true) {
      return err(
        "sensitivity_denied",
        `entry ${entry.id} has sensitivity=restricted; pass allow_restricted=true to import`,
        { entry_id: entry.id }
      );
    }
    // 4. project identity. We require that a
    //    project entry carries a `project_id`
    //    (or a `project_path` that the apply
    //    phase can resolve). The apply phase
    //    uses the strict_existing resolver, so a
    //    `project_id` that has not been
    //    registered will fail at apply time.
    //    Here we just enforce the field shape.
    if (entry.scope === "project") {
      const projectId = entry.project_id;
      if (projectId === undefined && entry.project_path === undefined) {
        return err(
          "invalid_schema",
          `entry ${entry.id} has project scope but no project_id / project_path`,
          { entry_id: entry.id }
        );
      }
    }
    // 5. id / revision conflict (only meaningful
    //    for `replace` policy; we preflight the
    //    CAS here so the apply phase never sees
    //    a drift).
    if (options.conflict === "replace") {
      const live = service.peekMemoryById(entry.id);
      if (live !== undefined && live.revision !== entry.revision) {
        return err(
          "revision_drift",
          `entry ${entry.id} revision drift: imported=${entry.revision} existing=${live.revision}`,
          { entry_id: entry.id }
        );
      }
    }
  }
  // 6. aggregate budget. The check sums the
  //    per-entry char_count and asks the live
  //    budget helper whether the target scope
  //    has room.
  const targetScope = scope;
  const targetProjectId = project_id;
  const aggregateChars = bundle.entries.reduce(
    (acc, e) => acc + (e.char_count ?? 0),
    0
  );
  const usage = service.store.getBudgetUsage({
    scope: targetScope,
    ...(targetProjectId !== undefined ? { project_id: targetProjectId } : {})
  });
  if (usage.index_chars + aggregateChars > Number.MAX_SAFE_INTEGER) {
    return err(
      "aggregate_budget",
      `aggregate bundle size (${aggregateChars} chars) would overflow the budget index`,
      { aggregate_chars: aggregateChars, index_chars: usage.index_chars }
    );
  }
  return ok({
    bundle,
    import_batch_id: newImportBatchId()
  });
}

/**
 * Plan an import: classify each imported entry as
 * insert / replace / merge / skip, and return the
 * plan. Does not mutate the live store.
 */
export function planImport(
  service: MemoryService,
  exportScopeDir: string,
  scope: MemoryScope,
  project_id: string | undefined,
  format: ImportFormat,
  options: ImportOptions
): ImportPlan {
  // Stage 15 PR-M0-3 (issue #4): the v1 contract
  // silently accepted `--format yaml` and let
  // `readEntries` return an empty list when no
  // matching files existed (it never reached
  // `parseEntries` for the unknown format). That
  // made a typo or a forgotten conversion succeed
  // with an empty plan. v2 fails fast on any
  // format other than `"json"`.
  if (format !== "json") {
    throw new Error(
      `unsupported import format: "${format}" (only "json" is supported; yaml was removed in v1.1)`
    );
  }
  // Preflight first. A preflight failure aborts
  // the import before any plan is built.
  const preflight = preflightImport(service, exportScopeDir, scope, project_id, format, options);
  if (!preflight.ok) {
    // Re-throw as a clear error so the CLI can
    // print exit code 1 with the failing entry.
    const where =
      typeof preflight.details?.entry_id === "string"
        ? ` (entry ${preflight.details.entry_id})`
        : "";
    throw new Error(`preflight failed: ${preflight.error}${where} — ${preflight.message}`);
  }
  const { bundle, import_batch_id } = preflight.value;
  const imported = bundle.entries;
  const historyMode: ImportHistoryMode = options.history_mode ?? "snapshot";
  const inserts: MemoryEntry[] = [];
  const replacements: { imported: MemoryEntry; existing: MemoryEntry }[] = [];
  const skipped: MemoryEntry[] = [];
  const decisions: ImportPlan["decisions"] = [];

  for (const entry of imported) {
    const existing = service.peekMemoryById(entry.id);
    if (existing === undefined) {
      inserts.push(entry);
      decisions.push({ kind: "insert", memory_id: entry.id });
      continue;
    }
    if (options.conflict === "keep") {
      skipped.push(entry);
      decisions.push({ kind: "skip", memory_id: entry.id, reason: "existing entry" });
      continue;
    }
    if (options.conflict === "replace") {
      replacements.push({ imported: entry, existing });
      decisions.push({ kind: "replace", memory_id: entry.id });
      continue;
    }
    if (options.conflict === "merge") {
      // Merge keeps the live entry's id and revision
      // but takes the higher importance / confidence
      // and the union of tags from the import.
      replacements.push({ imported: mergeEntries(existing, entry), existing });
      decisions.push({ kind: "merge", memory_id: entry.id });
      continue;
    }
    // fail
    throw new Error(`import conflict: memory_id=${entry.id} already exists (policy=fail)`);
  }

  return {
    manifest: bundle.manifest,
    scope,
    ...(project_id !== undefined ? { project_id } : {}),
    generation: bundle.generation,
    bundle_hash: bundle.bundle_hash,
    import_batch_id,
    history_mode: historyMode,
    inserts,
    replacements,
    skipped,
    decisions
  };
}

function mergeEntries(existing: MemoryEntry, imported: MemoryEntry): MemoryEntry {
  const tags = [...new Set([...existing.tags, ...imported.tags])];
  return {
    ...existing,
    importance: Math.max(existing.importance, imported.importance) as MemoryEntry["importance"],
    confidence: Math.max(existing.confidence, imported.confidence) as MemoryEntry["confidence"],
    tags,
    body: imported.body.length > existing.body.length ? imported.body : existing.body
  };
}

/**
 * Apply a plan to the live store. The plan was built by
 * `planImport`; applying it does the actual
 * remember / update calls. Each call goes through the
 * normal validation pipeline (scope, secret, budget).
 *
 * Stage 16 v1.1.1 PR-4 (issue #13): every applied entry
 * is forced to `trust_level: "imported"` unless the
 * caller passed `restore_trust: true` AND the plan's
 * history mode is `full_history`. The force happens at
 * the entry copy boundary so the original bundle bytes
 * stay untouched.
 *
 * The apply stamps `import_batch_id` and `bundle_hash`
 * on every audit event generated by the apply.
 *
 * Stage 15 PR-M0-3 (issue #4, spec § 6.7): the entire
 * apply is wrapped in a single `BEGIN IMMEDIATE`
 * transaction so a failure on entry N rolls back
 * entries 1..N-1. The DB is either fully imported or
 * not touched at all (all-or-nothing).
 */
export function applyImport(
  service: MemoryService,
  plan: ImportPlan,
  options: ImportOptions
): { applied: number; applied_ids: string[]; errors: string[] } {
  if (options.dry_run) {
    return { applied: 0, applied_ids: [], errors: [] };
  }
  let applied = 0;
  const applied_ids: string[] = [];
  const restoreTrust = options.restore_trust === true && plan.history_mode === "full_history";
  // We perform the entire apply in a single
  // transaction. The store's `transaction` helper
  // opens a `BEGIN IMMEDIATE`, runs the work, and
  // commits on success; any throw inside the work
  // callback rolls back.
  service.store.transaction(() => {
    for (const entry of plan.inserts) {
      const normalised: MemoryEntry = {
        ...entry,
        // Force `trust_level` to "imported" unless
        // the explicit trusted-bundle mechanism is
        // in play.
        trust_level: restoreTrust ? entry.trust_level ?? "imported" : "imported"
      };
      service.writeInsertImportedEntry(normalised, options.actor);
      applied += 1;
      applied_ids.push(entry.id);
    }
    for (const { imported, existing } of plan.replacements) {
      if (imported.revision !== existing.revision && options.conflict === "replace") {
        throw new Error(
          `replace ${imported.id}: revision drift (imported=${imported.revision} existing=${existing.revision})`
        );
      }
      const normalised: MemoryEntry = {
        ...imported,
        trust_level: restoreTrust ? imported.trust_level ?? "imported" : "imported"
      };
      const result = service.updateMemory(existing.id, entryToUpdateInput(normalised));
      if (!result.ok) {
        throw new Error(`update ${imported.id}: ${result.error}`);
      }
      applied += 1;
      applied_ids.push(imported.id);
    }
  });
  return { applied, applied_ids, errors: [] };
}

function entryToUpdateInput(entry: MemoryEntry): Parameters<MemoryService["updateMemory"]>[1] {
  return {
    topic: entry.topic,
    title: entry.title,
    body: entry.body,
    tags: entry.tags,
    importance: entry.importance,
    confidence: entry.confidence,
    ...(entry.expires_at !== undefined ? { expires_at: entry.expires_at } : {}),
    ...(entry.review_after !== undefined ? { review_after: entry.review_after } : {}),
    expected_revision: entry.revision
  };
}

/**
 * Stage 16 v1.1.1 PR-4 (issue #13): `MemoryEntry` carries
 * rows-only fields (id, revision, status, audit, ...)
 * that the `validateRememberInput` Zod schema does not
 * accept. The preflight strips them down to the
 * `RememberInput` shape so the schema validation runs
 * against exactly the same fields the live remember
 * path validates.
 */
function entryToRememberInput(entry: MemoryEntry): Record<string, unknown> {
  return {
    scope: entry.scope,
    ...(entry.project_id !== undefined ? { project_id: entry.project_id } : {}),
    ...(entry.project_path !== undefined ? { project_path: entry.project_path } : {}),
    type: entry.type,
    topic: entry.topic,
    title: entry.title,
    body: entry.body,
    tags: entry.tags,
    source: entry.source,
    importance: entry.importance,
    confidence: entry.confidence,
    // The preflight schema treats `expires_at` /
    // `review_after` as optional strings; the live
    // `MemoryEntry` represents the absence of the
    // field as `null`. The RememberInput shape has
    // no `null`, so we drop the field entirely when
    // the value is null.
    ...(entry.expires_at !== undefined && entry.expires_at !== null
      ? { expires_at: entry.expires_at }
      : {}),
    ...(entry.review_after !== undefined && entry.review_after !== null
      ? { review_after: entry.review_after }
      : {}),
    ...(entry.supersedes !== undefined && entry.supersedes.length > 0
      ? { supersedes: entry.supersedes }
      : {}),
    // Stage 16 v1.1.1 PR-7 (issue #17, spec § 5.4):
    // memory semantics controlled fields. The
    // bundle already has these (v1.1.0+);
    // round-tripping them through preflight lets
    // the validator catch a malformed bundle
    // (e.g. `valid_from > valid_until`) before
    // any row is written. `null` and `undefined`
    // are both treated as "absent" because the
    // live `MemoryEntry` represents the absence
    // as `null` while the `RememberInput` shape
    // has no `null`.
    tier: entry.tier,
    pinned: entry.pinned,
    ...(entry.valid_from !== undefined && entry.valid_from !== null
      ? { valid_from: entry.valid_from }
      : {}),
    ...(entry.valid_until !== undefined && entry.valid_until !== null
      ? { valid_until: entry.valid_until }
      : {}),
    sensitivity: entry.sensitivity,
    // The bundle's `trust_level` is forced to
    // `"imported"` by `applyImport` regardless of
    // what the bundle declares (unless the caller
    // passes `restore_trust: true` AND
    // `history_mode === "full_history"`). The
    // preflight deliberately OMITS the field so
    // the validator doesn't see a bundle-declared
    // `user_confirmed` and reject it; the
    // down-to-`imported` policy is enforced at
    // apply time, not preflight. The preflight
    // is about whether the entry can be written
    // at all, not about what trust tier it ends
    // up with.
    //
    // The other fields (tier, pinned, sensitivity,
    // valid_from, valid_until) are preserved
    // because they affect the entry shape itself.
    trust_level: "agent_observed"
  };
}

/**
 * High-level: plan + apply in one call. Returns the
 * full plan + the apply summary. When `dry_run` is
 * true the plan is built but not applied.
 */
export function importMemoryExport(
  service: MemoryService,
  exportScopeDir: string,
  scope: MemoryScope,
  project_id: string | undefined,
  format: ImportFormat,
  options: ImportOptions
): ImportResult {
  const started = Date.now();
  const plan = planImport(service, exportScopeDir, scope, project_id, format, options);
  const apply = applyImport(service, plan, options);
  return {
    applied:
      options.dry_run
        ? false
        : apply.errors.length === 0 &&
          (apply.applied > 0 || (plan.inserts.length === 0 && plan.replacements.length === 0)),
    plan,
    duration_ms: Date.now() - started,
    applied_ids: apply.applied_ids,
    import_batch_id: plan.import_batch_id
  };
}
