// src/portability/importer.ts
//
// Stage 13 PR10 (spec § 6.7): the import side of the
// portability contract. `importMemoryExport(root, ...)`
// reads a previously-exported scope (the manifest +
// per-topic files) and replays the entries into a live
// `MemoryService`. The import is the inverse of the
// export; it is the only supported way to populate a
// fresh DB from an external data source.
//
// Conflict policy (spec § 6.7):
//   - keep:      skip entries that already exist in the
//                live store; new entries are imported.
//   - replace:   overwrite the live entry with the
//                imported one. The imported entry must
//                carry a `revision` that matches the
//                live `revision` (CAS-style safety), or
//                the import refuses.
//   - merge:     combine tags + body, preserve the
//                higher importance / confidence.
//   - fail:      any conflict aborts the whole import
//                without writing anything.
//
// Stage 16 v1.1.1 PR-4 (issue #13): every import goes
// through a preflight phase that reuses the live write
// validators. The preflight runs BEFORE any mutation
// and refuses the entire plan if any entry fails:
//   - schema / enum validation (validateRememberInput);
//   - secret detection (detectSecrets on body);
//   - sensitivity policy (`restricted` may not leave
//     the source DB without an explicit override);
//   - project identity (strict_existing mode —
//     `project_path` resolves, `project_id`-only
//     rejects unless the identity is already
//     registered);
//   - aggregate batch budget (sum of the per-entry
//     sizes must fit the target budget);
//   - id / revision conflict policy (CAS check).
//
// Stage 16 v1.1.1 PR-4 (issue #13): every imported
// entry's `trust_level` is forced to `"imported"`. A
// re-hashed but tampered bundle that carries
// `user_confirmed` is downgraded on apply. A stronger
// trust decision can only be restored by an explicit
// `restore_trust` flag (the trusted-bundle mechanism).
//
// Stage 16 v1.1.1 PR-4 (issue #13): every import
// generates a stable `import_batch_id` and a
// `bundle_hash`. Both are recorded on every
// `audit_events` row generated by the apply, so a
// later reviewer can trace the row back to the exact
// bundle that produced it.
//
// Stage 16 v1.1.1 PR-4 (issue #13): two history modes.
//   - `snapshot` (default) imports the current entry
//     fields only. The live row starts at revision 1
//     with a single `created` audit event stamped by
//     the import batch.
//   - `full_history` imports the entries PLUS the
//     attached `memory_revisions` rows and the
//     related `audit_events`. The revision ordering
//     and the audit chain are preserved end-to-end.
//     Only `restore_trust` + `full_history` together
//     can re-claim a non-imported `trust_level`.
//
// Dry-run mode returns the plan (the entries that
// would be inserted / replaced / merged) without
// mutating the live store. This is the safe default
// for the CLI.

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  type MemoryBudget,
  type MemoryEntry,
  type MemoryScope,
  type Result
} from "../domain.js";
import { err, ok } from "../domain.js";
import { detectSecrets } from "../secret-detector.js";
import { validateRememberInput } from "../write-validator.js";
import { type BudgetUsage } from "../sqlite-store.js";
import {
  projectBatchBudget,
  type BatchBudgetExceededCode,
  type BatchOp
} from "../budget-governor.js";
import { budgetFor } from "../services/memory-service-helpers.js";
import type { MemoryService } from "../memory-service.js";
import { ProjectIdentityResolver } from "../scope-resolver.js";
import { readManifest, verifyManifest, MANIFEST_FILENAME, type Manifest } from "./manifest.js";
import {
  computeBundleHash,
  detectBundleGeneration,
  newImportBatchId,
  normaliseBundle,
  type BundleGeneration,
  type NormalisedBundle
} from "./migration-adapter.js";

export type ConflictPolicy = "keep" | "replace" | "merge" | "fail";

export type ImportHistoryMode = "snapshot" | "full_history";

export type ImportSensitivityPolicy = "normal" | "private" | "restricted";

/**
 * Preflight errors. A preflight failure is a
 * contract-level rejection of the bundle, distinct
 * from a per-entry write error. The preflight phase
 * returns a structured `{ ok: false, error, ... }`
 * so the CLI can print the failing entry id +
 * reason without leaking the entry body. The
 * failing entry id (if any) is in `details.entry_id`.
 */
export type PreflightError =
  | "invalid_schema"
  | "invalid_state"
  | "secret_detected"
  | "sensitivity_denied"
  | "identity_conflict"
  | "aggregate_budget"
  | "revision_drift"
  | "bundle_garbled"
  | "unauthorized";

export type PreflightResult = Result<
  {
    bundle: NormalisedBundle;
    import_batch_id: string;
    /**
     * Stage 18 v1.1.2 (issue #24, task 5):
     * deterministic plan: per-entry decisions
     * plus the `before` / `after` budget summary
     * computed from the live budget usage.
     */
    preflight: PreflightPlan;
  },
  PreflightError
>;

/**
 * Stage 18 v1.1.2 (issue #24, task 5): the
 * deterministic preflight surface. The plan is
 * inspectable and reproducible: the same bundle
 * + the same live store produce the same plan
 * (the `before` usage is sampled from the
 * store at preflight time; the `after` is
 * computed by `projectBatchBudget`). The plan
 * is also the audit surface for the preflight
 * (`audit_events` can record the
 * `before` / `after` summary so a reviewer
 * later knows what the live budget looked
 * like at preflight time).
 */
export type PreflightPlanDecision =
  | { kind: "insert"; memory_id: string }
  | { kind: "replace"; memory_id: string; existing_id: string }
  | { kind: "merge"; memory_id: string; existing_id: string }
  | { kind: "skip"; memory_id: string; reason: string }
  | { kind: "reject"; memory_id: string; reason: string };

export type PreflightPlan = {
  /**
   * Per-entry decision, in import order. The
   * preflight attaches a `reject` decision when
   * AND only when the entry was the failing one
   * (the preflight is fail-fast: the first
   * failing entry's decision is `reject`, every
   * earlier entry's decision is `insert` /
   * `replace` / `merge` / `skip`). The CLI can
   * surface the `before` budget summary even
   * on a failed preflight.
   */
  decisions: PreflightPlanDecision[];
  budget: {
    /** The live budget usage captured at preflight time. */
    before: BudgetUsage;
    /** The projected budget after the batch (when all ops succeed). */
    after: BudgetUsage;
    /** The configured budget limits (project / global). */
    active_budget: MemoryBudget;
    /** Net change to `active_chars` (`batch_chars - releases`). */
    batch_chars: number;
    /** Sum of `char_count` released by replaces / merges. */
    releases: number;
    /** Net change to `active_chars`. */
    net_chars: number;
    /** Net change to `index_chars`. */
    net_index_chars: number;
    /** Count of inserts / replaces / merges. */
    inserts: number;
    replacements: number;
    merges: number;
  };
};

export type ImportPlan = {
  manifest: Manifest;
  scope: MemoryScope;
  project_id?: string;
  /** Bundle generation after the migration adapter. */
  generation: BundleGeneration;
  /** Stable bundle hash (sha256 of the normalised bundle). */
  bundle_hash: string;
  /** UUID identifying this import run. */
  import_batch_id: string;
  /** `snapshot` or `full_history`. */
  history_mode: ImportHistoryMode;
  /** Entries that will be inserted (no existing id). */
  inserts: MemoryEntry[];
  /** Entries that will be replaced (existing id, conflict policy != keep). */
  replacements: { imported: MemoryEntry; existing: MemoryEntry }[];
  /** Entries that will be skipped under `keep`. */
  skipped: MemoryEntry[];
  /** Per-entry status, in import order. */
  decisions: Array<
    | { kind: "insert"; memory_id: string }
    | { kind: "replace"; memory_id: string }
    | { kind: "merge"; memory_id: string }
    | { kind: "skip"; memory_id: string; reason: string }
  >;
  /**
   * Stage 18 v1.1.2 (issue #24, task 5): the
   * deterministic preflight plan (v1 summary
   * + per-entry decisions). The apply phase
   * uses this to re-validate at apply time.
   */
  preflight?: PreflightPlan;
};

export type ImportOptions = {
  conflict: ConflictPolicy;
  dry_run: boolean;
  actor: string;
  /**
   * When true (the default), abort on a manifest
   * hash mismatch. Stage 15 PR-M0-3 (issue #4, spec
   * § 6.7) flips the default to true — the v1
   * contract made the verification opt-in, which
   * meant an entry could be silently dropped from
   * the export without the import noticing.
   */
  require_clean_manifest?: boolean;
  /**
   * Stage 16 v1.1.1 PR-4 (issue #13). `snapshot`
   * (default) imports the current entry fields
   * only. `full_history` also restores the
   * `memory_revisions` and `audit_events` chain.
   */
  history_mode?: ImportHistoryMode;
  /**
   * Stage 16 v1.1.1 PR-4 (issue #13). The live
   * sensitivity policy. `restricted` entries may
   * not leave the source DB unless the caller
   * passes `allow_restricted: true`.
   */
  allow_restricted?: boolean;
  /**
   * Stage 16 v1.1.1 PR-4 (issue #13). When true,
   * a `full_history` import is allowed to restore
   * a `user_confirmed` trust tier from the bundle.
   * Default `false`. The trusted-bundle mechanism
   * in this release is the explicit
   * `--restore-trust` CLI flag; remote signing
   * infrastructure is explicitly a non-goal.
   *
   * Stage 18 v1.1.2 (issue #23, ADR-0001): the
   * `restore_trust` flag is now gated on a valid
   * `capability` (see below). A bare
   * `restore_trust: true` without a capability is
   * rejected at preflight with `unauthorized`.
   * The flag itself is preserved for backward
   * compatibility; the v1.1.2 contract pins the
   * authorization decision on the
   * `import_trust_restore` capability type.
   */
  restore_trust?: boolean;
  /**
   * Stage 18 v1.1.2 (issue #23, ADR-0001): the
   * operator capability token. Required when the
   * import would re-claim a non-`imported` trust
   * tier (`restore_trust: true` + `full_history`)
   * OR a `sensitivity: "restricted"` row
   * (`allow_restricted: true`). The preflight
   * calls `MemoryService.adminCapabilityStore.authorize(...)`
   * on the matching capability type and rejects
   * the bundle with `unauthorized` when the
   * capability is missing, malformed, or
   * mismatched. The token is NEVER surfaced in
   * the error message; the failure surfaces the
   * stable `unauthorized` reason code.
   */
  capability?: string;
};

export type ImportResult = {
  applied: boolean;
  plan: ImportPlan;
  duration_ms: number;
  /** Ids of the entries that were actually written. */
  applied_ids: string[];
  /** The import batch id (also on the plan). */
  import_batch_id: string;
};

/**
 * Read the export directory's MANIFEST.json and the
 * per-topic files into a flat list of entries. The
 * caller passes the scope + project_id that the export
 * was produced for; the importer does not infer it
 * from the manifest alone (project_id is a path
 * segment, the manifest only records the scope label).
 */
export function readImportBundle(exportScopeDir: string, scope: MemoryScope, project_id?: string): Manifest {
  if (!existsSync(exportScopeDir)) {
    throw new Error(`export directory not found: ${exportScopeDir}`);
  }
  if (!existsSync(join(exportScopeDir, MANIFEST_FILENAME))) {
    // Stage 16 v1.1.1 PR-4 (issue #13): the v1
    // path threw `manifest not found` for v0
    // bundles. The migration adapter now
    // synthesises a v1 manifest for v0 bundles,
    // so the caller should not hit this error in
    // normal use; the throw stays for a corrupt
    // export directory that has no manifest and
    // no `topics/` subdir.
    throw new Error(
      `export directory has no MANIFEST.json: ${exportScopeDir} (try the migration-adapter to read pre-v1 bundles)`
    );
  }
  const manifest = readManifest(exportScopeDir);
  if (manifest.scope !== expectedScopeLabel(scope, project_id)) {
    throw new Error(
      `manifest scope mismatch: manifest=${manifest.scope} expected=${expectedScopeLabel(scope, project_id)}`
    );
  }
  return manifest;
}

function expectedScopeLabel(scope: MemoryScope, project_id?: string): string {
  return scope === "project" ? `project/${project_id ?? "unknown-project"}` : "global";
}

export type ImportFormat = "json";

function extensionFor(format: ImportFormat): string {
  // JSON-only now (Stage 15 PR-M0-3, issue #4).
  return format;
}

function parseEntries(body: string, format: "markdown" | "json"): MemoryEntry[] {
  if (format === "markdown") {
    throw new Error("importing from markdown is not supported; use the json export");
  }
  if (format !== "json") {
    throw new Error(`unsupported import format: ${format} (only "json" is supported)`);
  }
  const parsed = JSON.parse(body) as { entries: MemoryEntry[] };
  return parsed.entries ?? [];
}

/**
 * Stage 16 v1.1.1 PR-4 (issue #13): the preflight
 * phase. Runs every entry through the live write
 * validators, plus the project identity check, the
 * sensitivity policy, the aggregate budget check, and
 * the id / revision CAS check. The preflight returns
 * either `{ ok: true, bundle, import_batch_id }` or
 * `{ ok: false, error, message, entry_id }`. A
 * preflight failure aborts the import; nothing is
 * written to the live store.
 *
 * The preflight also generates the `import_batch_id`
 * and computes the `bundle_hash`. Both are returned
 * so the apply phase can stamp them on every audit
 * event.
 */
export function preflightImport(
  service: MemoryService,
  exportScopeDir: string,
  scope: MemoryScope,
  project_id: string | undefined,
  format: ImportFormat,
  options: ImportOptions
): PreflightResult {
  // Bundle normalisation (covers v0 / v1 / v2
  // bundles). The adapter is a no-op for v2
  // bundles.
  let bundle: NormalisedBundle;
  try {
    bundle = normaliseBundle(exportScopeDir, format);
  } catch (e) {
    return err("bundle_garbled", e instanceof Error ? e.message : String(e), {
      reason: e instanceof Error ? e.message : String(e)
    });
  }
  // Re-verify the manifest. The adapter does not
  // touch on-disk bytes for v1 / v2 bundles, so a
  // post-normalisation verify still catches a
  // tampered file.
  if (options.require_clean_manifest !== false) {
    if (existsSync(join(exportScopeDir, MANIFEST_FILENAME))) {
      const manifestOnDisk = readManifest(exportScopeDir);
      const mismatches = verifyManifest(exportScopeDir, manifestOnDisk);
      if (mismatches.length > 0) {
        return err(
          "bundle_garbled",
          `manifest hash mismatch: ${mismatches.length} file(s) do not match the manifest (${mismatches.join(", ")})`,
          { mismatches }
        );
      }
    }
  }
  // Stage 18 v1.1.2 (issue #23, ADR-0001): the
  // import-time admin boundary. The preflight
  // determines whether the bundle requires
  // capability authorization (a `restore_trust`
  // import OR a `restricted`-sensitivity entry)
  // and, when it does, calls the
  // `MemoryService.adminCapabilityStore` to
  // authorise the import. A missing or invalid
  // capability fails closed at preflight (the
  // bundle is rejected with `unauthorized`
  // before any entry is written).
  const requiresImportTrustRestore = options.history_mode === "full_history" && options.restore_trust === true;
  const requiresImportRestricted = bundle.entries.some((e) => e.sensitivity === "restricted");
  if ((requiresImportTrustRestore || requiresImportRestricted) && service.adminCapabilityStore === undefined) {
    return err(
      "unauthorized",
      `import requires an operator capability; run \`agent-recall admin grant\` and pass the token via the \`capability\` import option`,
      {
        capability_type: requiresImportTrustRestore ? "import_trust_restore" : "import_restricted"
      }
    );
  }
  if (requiresImportTrustRestore || requiresImportRestricted) {
    const capability = options.capability;
    if (capability === undefined) {
      return err(
        "unauthorized",
        `import requires a capability token; pass the option \`capability: "<token>"\` on the import call`,
        {
          capability_type: requiresImportTrustRestore ? "import_trust_restore" : "import_restricted"
        }
      );
    }
    const decision = service.adminCapabilityStore!.authorize({
      capability,
      capability_type: requiresImportTrustRestore ? "import_trust_restore" : "import_restricted",
      requestContext: {
        actor_id: "agent:importer" as never,
        request_id: `import-preflight-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      }
    });
    if (!decision.ok) {
      return err(
        "unauthorized",
        `import capability check failed: ${decision.reason}`,
        { reason: decision.reason, capability_type: requiresImportTrustRestore ? "import_trust_restore" : "import_restricted" }
      );
    }
  }

  // For each entry: schema / secret / sensitivity
  // / id / revision. The live project identity
  // resolver runs in `strict_existing` mode so a
  // `project_id`-only input that lacks a registered
  // identity is rejected at the preflight stage
  // (rather than silently creating a new identity
  // from the bundle).
  // v1.1.2 (issue #21): the preflight constructs a
  // strict resolver from the target store and
  // runs it for every project-scoped entry. The
  // resolver surfaces `identity_status: "bound"`
  // when a `project_identities` row exists and
  // `invalid_scope` when the bundle tries to
  // import into an unknown / unbound namespace.
  // Path-supplied entries are still allowed to
  // register an identity (the strict resolver's
  // path branch routes through
  // `resolveMemoryScopeWithStore(this.store, ...)`)
  // so a v1 export that carries the original
  // `project_path` per entry is honoured.
  //
  // Stage 18 v1.1.2 (issue #24, task 5): the
  // preflight now ALSO accumulates per-entry
  // batch ops (insert / replace / merge / skip)
  // and projections so the post-validation
  // aggregate-budget check is computed against
  // the REAL configured limits (not
  // `Number.MAX_SAFE_INTEGER`). The plan is
  // surfaced on both success and failure so the
  // CLI can inspect the partial state.
  const identityResolver = new ProjectIdentityResolver(service.store, options.actor);
  // Snapshot the live usage ONCE — the
  // per-entry loop is read-only against the
  // store so the `before` value is stable for
  // the duration of the preflight.
  const targetScope = scope;
  const targetProjectId = project_id;
  const usage = service.store.getBudgetUsage({
    scope: targetScope,
    ...(targetProjectId !== undefined ? { project_id: targetProjectId } : {})
  });
  const activeBudget = budgetFor(service.store, {
    scope: targetScope,
    ...(targetProjectId !== undefined ? { project_id: targetProjectId } : {})
  });
  const batchOps: BatchOp[] = [];
  const decisions: PreflightPlanDecision[] = [];
  // Build the decisions / ops list as we walk
  // the bundle. The first failing entry's
  // decision is `reject`; the preflight returns
  // `err("...","...", { entry_id, preflight })`
  // so the CLI can still surface the partial
  // plan.
  const failFast = (
    error: PreflightError,
    message: string,
    entryId: string,
    details: Record<string, unknown> = {}
  ): PreflightResult => {
    decisions.push({ kind: "reject", memory_id: entryId, reason: error });
    const preflight: PreflightPlan = {
      decisions,
      budget: {
        before: usage,
        after: usage,
        active_budget: activeBudget,
        batch_chars: 0,
        releases: 0,
        net_chars: 0,
        net_index_chars: 0,
        inserts: 0,
        replacements: 0,
        merges: 0
      }
    };
    return err(error, message, { entry_id: entryId, preflight, ...details });
  };
  for (const entry of bundle.entries) {
    // 1. schema / enum / secret. The validator may
    // reject the entry with `invalid_schema` OR
    // `secret_detected`; the preflight surfaces the
    // original code so the CLI can branch on it
    // without re-parsing the message.
    const validated = validateRememberInput(entryToRememberInput(entry));
    if (!validated.ok) {
      const preflightError: PreflightError = validated.error;
      return failFast(
        preflightError,
        `entry ${entry.id} failed ${validated.error}: ${validated.message}`,
        entry.id,
        { ...(validated.details ?? {}) }
      );
    }
    // 2. secret detection (the validator already
    // ran this on body + title + tags; we re-run
    //    on body so the preflight error names the
    //    field explicitly).
    const findings = detectSecrets(entry.body, "body");
    if (findings.length > 0) {
      return failFast(
        "secret_detected",
        `entry ${entry.id} contains a potential secret (categories: ${findings.map((f) => f.category).join(", ")})`,
        entry.id
      );
    }
    // 3. sensitivity policy.
    // Stage 18 v1.1.2 (issue #23, ADR-0001): the
    // `allow_restricted` flag is now gated on the
    // `CapabilityStore`. The flag itself is
    // preserved for backward compatibility (older
    // CLI scripts pass it without a capability),
    // but the v1.1.2 contract pins the
    // authorization decision on the
    // `sensitivity_restricted` /
    // `import_restricted` capability. A bare
    // `allow_restricted: true` without a
    // capability is rejected at preflight.
    if (entry.sensitivity === "restricted" && options.allow_restricted !== true) {
      return failFast(
        "sensitivity_denied",
        `entry ${entry.id} has sensitivity=restricted; pass allow_restricted=true AND an operator capability to import`,
        entry.id
      );
    }
    // 4. project identity. v1.1.2 (issue #21): the
    //    preflight now runs the strict resolver on
    //    every project-scoped entry. A `project_id`
    //    that has not been registered on the target
    //    store surfaces `identity_conflict` so the
    //    bundle is rejected at preflight (the apply
    //    phase used to be the only gate, and the
    //    preflight's "we'll just enforce the field
    //    shape" comment was wrong — apply does not
    //    run the resolver on inserts, so an
    //    unbound `project_id` would silently
    //    create a new namespace).
    if (entry.scope === "project") {
      const projectId = entry.project_id;
      const projectPath = entry.project_path;
      if (projectId === undefined && projectPath === undefined) {
        return failFast(
          "invalid_schema",
          `entry ${entry.id} has project scope but no project_id / project_path`,
          entry.id
        );
      }
      const identityResolved = identityResolver.resolve(
        {
          scope: "project",
          ...(projectId !== undefined ? { project_id: projectId } : {}),
          ...(projectPath !== undefined ? { project_path: projectPath } : {})
        },
        "strict_existing"
      );
      if (!identityResolved.ok) {
        return failFast(
          "identity_conflict",
          `entry ${entry.id} targets an unbound / conflicting project: ${identityResolved.message}`,
          entry.id,
          {
            ...(projectId !== undefined ? { project_id: projectId } : {}),
            ...(projectPath !== undefined ? { project_path: projectPath } : {})
          }
        );
      }
    }
    // 5. id / revision conflict (only meaningful
    //    for `replace` policy; we preflight the
    //    CAS here so the apply phase never sees
    //    a drift).
    const live = service.peekMemoryById(entry.id);
    if (options.conflict === "replace" && live !== undefined && live.revision !== entry.revision) {
      return failFast(
        "revision_drift",
        `entry ${entry.id} revision drift: imported=${entry.revision} existing=${live.revision}`,
        entry.id
      );
    }
    // 6. classify the entry into the batch
    //    op. The preflight is the single
    //    source of truth for insert/replace/
    //    merge/skip so the budget check is
    //    computed against the same
    //    classification the apply phase uses.
    if (live === undefined) {
      batchOps.push({ kind: "insert", entry });
      decisions.push({ kind: "insert", memory_id: entry.id });
    } else if (options.conflict === "keep") {
      decisions.push({ kind: "skip", memory_id: entry.id, reason: "existing entry" });
    } else if (options.conflict === "replace") {
      batchOps.push({ kind: "replace", entry, existing: live });
      decisions.push({ kind: "replace", memory_id: entry.id, existing_id: live.id });
    } else if (options.conflict === "merge") {
      batchOps.push({ kind: "merge", entry, existing: live });
      decisions.push({ kind: "merge", memory_id: entry.id, existing_id: live.id });
    } else {
      // fail policy: preflight rejects the
      // whole batch on the first conflict.
      // The error message preserves the
      // v1.1.1 PR-4 wording (`import
      // conflict: ...`) so the CLI's regex
      // matcher in `test/portability-import.test.ts`
      // keeps working.
      return failFast(
        "identity_conflict",
        `import conflict: memory_id=${entry.id} already exists (policy=fail)`,
        entry.id
      );
    }
  }
  // 7. aggregate budget. The check sums the
  //    per-entry char_count / index chars and
  //    asks the live budget helper whether the
  //    target scope has room. The check is
  //    computed against the REAL configured
  //    limits (the v1.1.2 contract; the v1.1.1
  //    PR-4 path used `Number.MAX_SAFE_INTEGER`
  //    as a placeholder for "no limit", which
  //    was useless).
  const batchProjection = projectBatchBudget({
    budget: activeBudget,
    usage,
    ops: batchOps
  });
  if (!batchProjection.ok) {
    const budgetError = batchProjection.error;
    const failingEntryId: string = batchOps.length > 0
      ? batchOps[batchOps.length - 1]!.entry.id
      : (bundle.entries[0]?.id ?? "unknown");
    const plan: PreflightPlan = {
      decisions,
      budget: {
        before: usage,
        after: budgetError.budget_after,
        active_budget: activeBudget,
        batch_chars: batchProjection.result.batch_chars,
        releases: batchProjection.result.releases,
        net_chars: batchProjection.result.net_chars,
        net_index_chars: batchProjection.result.net_index_chars,
        inserts: batchProjection.result.insert_count,
        replacements: batchProjection.result.replace_count,
        merges: batchProjection.result.merge_count
      }
    };
    return err(
      "aggregate_budget",
      aggregateBudgetMessage(budgetError.code, budgetError.observed, budgetError.limit, activeBudget, budgetError.budget_after),
      {
        entry_id: failingEntryId,
        preflight: plan,
        budget_code: budgetError.code,
        observed: budgetError.observed,
        limit: budgetError.limit,
        budget_after: budgetError.budget_after
      }
    );
  }
  const plan: PreflightPlan = {
    decisions,
    budget: {
      before: usage,
      after: batchProjection.result.after,
      active_budget: activeBudget,
      batch_chars: batchProjection.result.batch_chars,
      releases: batchProjection.result.releases,
      net_chars: batchProjection.result.net_chars,
      net_index_chars: batchProjection.result.net_index_chars,
      inserts: batchProjection.result.insert_count,
      replacements: batchProjection.result.replace_count,
      merges: batchProjection.result.merge_count
    }
  };
  return ok({
    bundle,
    import_batch_id: newImportBatchId(),
    preflight: plan
  });
}

function aggregateBudgetMessage(
  code: BatchBudgetExceededCode,
  observed: number,
  limit: number,
  budget: MemoryBudget,
  after: BudgetUsage
): string {
  switch (code) {
    case "max_active_entries":
      return `aggregate budget exceeded: active_entries ${observed} > max_active_entries ${limit} (max_total_chars=${budget.max_total_chars}, max_index_chars=${budget.max_index_chars})`;
    case "max_total_chars":
      return `aggregate budget exceeded: active_chars ${observed} > max_total_chars ${limit} (after aggregate=${after.active_chars})`;
    case "max_topic_chars":
      return `aggregate budget exceeded: per-topic chars ${observed} > max_topic_chars ${limit}`;
    case "max_index_chars":
      return `aggregate budget exceeded: index_chars ${observed} > max_index_chars ${limit} (after aggregate=${after.index_chars})`;
  }
}

/**
 * Plan an import: classify each imported entry as
 * insert / replace / merge / skip, and return the
 * plan. Does not mutate the live store.
 */
export function planImport(
  service: MemoryService,
  exportScopeDir: string,
  scope: MemoryScope,
  project_id: string | undefined,
  format: ImportFormat,
  options: ImportOptions
): ImportPlan {
  // Stage 15 PR-M0-3 (issue #4): the v1 contract
  // silently accepted `--format yaml` and let
  // `readEntries` return an empty list when no
  // matching files existed (it never reached
  // `parseEntries` for the unknown format). That
  // made a typo or a forgotten conversion succeed
  // with an empty plan. v2 fails fast on any
  // format other than `"json"`.
  if (format !== "json") {
    throw new Error(
      `unsupported import format: "${format}" (only "json" is supported; yaml was removed in v1.1)`
    );
  }
  // Preflight first. A preflight failure aborts
  // the import before any plan is built.
  const preflight = preflightImport(service, exportScopeDir, scope, project_id, format, options);
  if (!preflight.ok) {
    // Re-throw as a clear error so the CLI can
    // print exit code 1 with the failing entry.
    const where =
      typeof preflight.details?.entry_id === "string"
        ? ` (entry ${preflight.details.entry_id})`
        : "";
    throw new Error(`preflight failed: ${preflight.error}${where} — ${preflight.message}`);
  }
  const { bundle, import_batch_id, preflight: preflightPlan } = preflight.value;
  const imported = bundle.entries;
  const historyMode: ImportHistoryMode = options.history_mode ?? "snapshot";
  const inserts: MemoryEntry[] = [];
  const replacements: { imported: MemoryEntry; existing: MemoryEntry }[] = [];
  const skipped: MemoryEntry[] = [];
  const decisions: ImportPlan["decisions"] = [];

  // The preflight already classified every
  // entry (insert / replace / merge / skip).
  // Iterate in the preflight's order so the
  // plan's `decisions` array matches the
  // preflight's `decisions` array (the
  // `before` / `after` summary is anchored on
  // the preflight's classification).
  const decisionById = new Map<string, PreflightPlanDecision>();
  for (const d of preflightPlan.decisions) {
    decisionById.set(d.memory_id, d);
  }
  for (const entry of imported) {
    const d = decisionById.get(entry.id);
    if (d === undefined) {
      // Should not happen: the preflight
      // walks every entry in `bundle.entries`.
      // If we get here, the bundle was tampered
      // with between preflight and plan; the
      // safe behaviour is to fail closed.
      throw new Error(`preflight plan is missing entry ${entry.id}`);
    }
    const existing = service.peekMemoryById(entry.id);
    if (d.kind === "insert") {
      inserts.push(entry);
      decisions.push({ kind: "insert", memory_id: entry.id });
      continue;
    }
    if (d.kind === "skip") {
      skipped.push(entry);
      decisions.push({ kind: "skip", memory_id: entry.id, reason: d.reason });
      continue;
    }
    if (d.kind === "replace") {
      if (existing === undefined) {
        // Race: the live row disappeared between
        // preflight and plan. The apply-time
        // revalidation will catch this; the plan
        // reclassifies as an insert.
        inserts.push(entry);
        decisions.push({ kind: "insert", memory_id: entry.id });
        continue;
      }
      replacements.push({ imported: entry, existing });
      decisions.push({ kind: "replace", memory_id: entry.id });
      continue;
    }
    if (d.kind === "merge") {
      if (existing === undefined) {
        inserts.push(entry);
        decisions.push({ kind: "insert", memory_id: entry.id });
        continue;
      }
      // Merge keeps the live entry's id and revision
      // but takes the higher importance / confidence
      // and the union of tags from the import.
      replacements.push({ imported: mergeEntries(existing, entry), existing });
      decisions.push({ kind: "merge", memory_id: entry.id });
      continue;
    }
    // The preflight tagged the entry as
    // `reject` — but the preflight is fail-fast
    // so we never reach here. The defensive
    // throw keeps the type narrow.
    throw new Error(`preflight plan has rejected entry ${entry.id}`);
  }

  return {
    manifest: bundle.manifest,
    scope,
    ...(project_id !== undefined ? { project_id } : {}),
    generation: bundle.generation,
    bundle_hash: bundle.bundle_hash,
    import_batch_id,
    history_mode: historyMode,
    inserts,
    replacements,
    skipped,
    decisions,
    preflight: preflightPlan
  };
}

function mergeEntries(existing: MemoryEntry, imported: MemoryEntry): MemoryEntry {
  const tags = [...new Set([...existing.tags, ...imported.tags])];
  return {
    ...existing,
    importance: Math.max(existing.importance, imported.importance) as MemoryEntry["importance"],
    confidence: Math.max(existing.confidence, imported.confidence) as MemoryEntry["confidence"],
    tags,
    body: imported.body.length > existing.body.length ? imported.body : existing.body
  };
}

/**
 * Apply a plan to the live store. The plan was built by
 * `planImport`; applying it does the actual
 * remember / update calls. Each call goes through the
 * normal validation pipeline (scope, secret, budget).
 *
 * Stage 16 v1.1.1 PR-4 (issue #13): every applied entry
 * is forced to `trust_level: "imported"` unless the
 * caller passed `restore_trust: true` AND the plan's
 * history mode is `full_history`. The force happens at
 * the entry copy boundary so the original bundle bytes
 * stay untouched.
 *
 * The apply stamps `import_batch_id` and `bundle_hash`
 * on every audit event generated by the apply.
 *
 * Stage 15 PR-M0-3 (issue #4, spec § 6.7): the entire
 * apply is wrapped in a single `BEGIN IMMEDIATE`
 * transaction so a failure on entry N rolls back
 * entries 1..N-1. The DB is either fully imported or
 * not touched at all (all-or-nothing).
 *
 * Stage 18 v1.1.2 (issue #24, task 5): the apply
 * re-validates the preflight's assumptions inside
 * the transaction. The preflight captures the
 * `(revisions, ids, aggregate budget)` snapshot at
 * plan time; the apply re-reads the live store
 * INSIDE the transaction and rejects the whole
 * batch when any of the assumptions drifted. A
 * preflight / apply race (a concurrent write
 * that bumped a row's revision) therefore
 * triggers an atomic rollback: the live store
 * is untouched, no `import_batches` row is
 * committed (Task 7 #26 will add the persistent
 * lineage surface; this task ships the
 * "don't write a completed batch row on a
 * failed apply" contract).
 */
export function applyImport(
  service: MemoryService,
  plan: ImportPlan,
  options: ImportOptions
): { applied: number; applied_ids: string[]; errors: string[] } {
  if (options.dry_run) {
    return { applied: 0, applied_ids: [], errors: [] };
  }
  let applied = 0;
  const applied_ids: string[] = [];
  const restoreTrust = options.restore_trust === true && plan.history_mode === "full_history";
  // We perform the entire apply in a single
  // transaction. The store's `transaction` helper
  // opens a `BEGIN IMMEDIATE`, runs the work, and
  // commits on success; any throw inside the work
  // callback rolls back.
  service.store.transaction(() => {
    // -----------------------------------------------------------------
    // Stage 18 v1.1.2 (issue #24, task 5): apply-time
    // revalidation. The preflight captured the
    // `(revisions, ids, aggregate budget)` snapshot at
    // plan time; the apply re-reads the live store
    // INSIDE the transaction and rejects the whole
    // batch when any of the assumptions drifted.
    // -----------------------------------------------------------------
    for (const { imported, existing } of plan.replacements) {
      // Re-read the live row inside the transaction
      // so a concurrent write between preflight and
      // apply is detected here.
      const liveNow = service.peekMemoryById(existing.id);
      if (liveNow === undefined) {
        throw new Error(
          `replace ${imported.id}: target row disappeared between preflight and apply (concurrent delete?)`
        );
      }
      if (options.conflict === "replace" && liveNow.revision !== imported.revision) {
        throw new Error(
          `replace ${imported.id}: revision drift (imported=${imported.revision} existing=${liveNow.revision})`
        );
      }
      if (options.conflict === "merge" && liveNow.revision !== imported.revision) {
        throw new Error(
          `merge ${imported.id}: revision drift (imported=${imported.revision} existing=${liveNow.revision})`
        );
      }
    }
    // Re-validate the aggregate budget invariant.
    // The preflight computed the projection against
    // `usage_before`; the apply re-reads the live
    // usage (which may have changed if a concurrent
    // write mutated the scope between the preflight
    // and the apply) and asserts the projection
    // still holds. The check is in-transaction so
    // the rollback is atomic.
    if (plan.preflight !== undefined) {
      const liveUsage = service.store.getBudgetUsage({
        scope: plan.scope,
        ...(plan.project_id !== undefined ? { project_id: plan.project_id } : {})
      });
      const reapply = projectBatchBudget({
        budget: plan.preflight.budget.active_budget,
        usage: liveUsage,
        ops: plan.preflight.decisions
          .filter((d): d is PreflightPlanDecision & { kind: "insert" | "replace" | "merge" } =>
            d.kind === "insert" || d.kind === "replace" || d.kind === "merge"
          )
          .map((d) => {
            const decision = d as PreflightPlanDecision & { kind: "insert" | "replace" | "merge" };
            const entry = plan.inserts.find((e) => e.id === decision.memory_id)
              ?? plan.replacements.find((r) => r.imported.id === decision.memory_id)?.imported;
            if (entry === undefined) {
              throw new Error(
                `apply revalidation cannot resolve entry ${decision.memory_id} from the plan`
              );
            }
            const existing = plan.replacements.find((r) => r.imported.id === decision.memory_id)?.existing;
            if (decision.kind === "insert") {
              return { kind: "insert" as const, entry };
            }
            if (decision.kind === "replace") {
              return { kind: "replace" as const, entry, ...(existing !== undefined ? { existing } : {}) };
            }
            return { kind: "merge" as const, entry, ...(existing !== undefined ? { existing } : {}) };
          })
      });
      if (!reapply.ok) {
        throw new Error(
          `aggregate budget drifted between preflight and apply: ${reapply.error.code} (observed=${reapply.error.observed}, limit=${reapply.error.limit})`
        );
      }
    }
    for (const entry of plan.inserts) {
      const normalised: MemoryEntry = {
        ...entry,
        // Force `trust_level` to "imported" unless
        // the explicit trusted-bundle mechanism is
        // in play.
        trust_level: restoreTrust ? entry.trust_level ?? "imported" : "imported"
      };
      service.writeInsertImportedEntry(normalised, options.actor);
      applied += 1;
      applied_ids.push(entry.id);
    }
    for (const { imported, existing } of plan.replacements) {
      const normalised: MemoryEntry = {
        ...imported,
        trust_level: restoreTrust ? imported.trust_level ?? "imported" : "imported"
      };
      const result = service.updateMemory(existing.id, entryToUpdateInput(normalised));
      if (!result.ok) {
        throw new Error(`update ${imported.id}: ${result.error}`);
      }
      applied += 1;
      applied_ids.push(imported.id);
    }
  });
  return { applied, applied_ids, errors: [] };
}

function entryToUpdateInput(entry: MemoryEntry): Parameters<MemoryService["updateMemory"]>[1] {
  return {
    topic: entry.topic,
    title: entry.title,
    body: entry.body,
    tags: entry.tags,
    importance: entry.importance,
    confidence: entry.confidence,
    ...(entry.expires_at !== undefined ? { expires_at: entry.expires_at } : {}),
    ...(entry.review_after !== undefined ? { review_after: entry.review_after } : {}),
    expected_revision: entry.revision
  };
}

/**
 * Stage 16 v1.1.1 PR-4 (issue #13): `MemoryEntry` carries
 * rows-only fields (id, revision, status, audit, ...)
 * that the `validateRememberInput` Zod schema does not
 * accept. The preflight strips them down to the
 * `RememberInput` shape so the schema validation runs
 * against exactly the same fields the live remember
 * path validates.
 */
function entryToRememberInput(entry: MemoryEntry): Record<string, unknown> {
  return {
    scope: entry.scope,
    ...(entry.project_id !== undefined ? { project_id: entry.project_id } : {}),
    ...(entry.project_path !== undefined ? { project_path: entry.project_path } : {}),
    type: entry.type,
    topic: entry.topic,
    title: entry.title,
    body: entry.body,
    tags: entry.tags,
    source: entry.source,
    importance: entry.importance,
    confidence: entry.confidence,
    // The preflight schema treats `expires_at` /
    // `review_after` as optional strings; the live
    // `MemoryEntry` represents the absence of the
    // field as `null`. The RememberInput shape has
    // no `null`, so we drop the field entirely when
    // the value is null.
    ...(entry.expires_at !== undefined && entry.expires_at !== null
      ? { expires_at: entry.expires_at }
      : {}),
    ...(entry.review_after !== undefined && entry.review_after !== null
      ? { review_after: entry.review_after }
      : {}),
    ...(entry.supersedes !== undefined && entry.supersedes.length > 0
      ? { supersedes: entry.supersedes }
      : {}),
    // Stage 16 v1.1.1 PR-7 (issue #17, spec § 5.4):
    // memory semantics controlled fields. The
    // bundle already has these (v1.1.0+);
    // round-tripping them through preflight lets
    // the validator catch a malformed bundle
    // (e.g. `valid_from > valid_until`) before
    // any row is written. `null` and `undefined`
    // are both treated as "absent" because the
    // live `MemoryEntry` represents the absence
    // as `null` while the `RememberInput` shape
    // has no `null`.
    tier: entry.tier,
    pinned: entry.pinned,
    ...(entry.valid_from !== undefined && entry.valid_from !== null
      ? { valid_from: entry.valid_from }
      : {}),
    ...(entry.valid_until !== undefined && entry.valid_until !== null
      ? { valid_until: entry.valid_until }
      : {}),
    sensitivity: entry.sensitivity,
    // The bundle's `trust_level` is forced to
    // `"imported"` by `applyImport` regardless of
    // what the bundle declares (unless the caller
    // passes `restore_trust: true` AND
    // `history_mode === "full_history"`). The
    // preflight deliberately OMITS the field so
    // the validator doesn't see a bundle-declared
    // `user_confirmed` and reject it; the
    // down-to-`imported` policy is enforced at
    // apply time, not preflight. The preflight
    // is about whether the entry can be written
    // at all, not about what trust tier it ends
    // up with.
    //
    // The other fields (tier, pinned, sensitivity,
    // valid_from, valid_until) are preserved
    // because they affect the entry shape itself.
    trust_level: "agent_observed"
  };
}

/**
 * High-level: plan + apply in one call. Returns the
 * full plan + the apply summary. When `dry_run` is
 * true the plan is built but not applied.
 */
export function importMemoryExport(
  service: MemoryService,
  exportScopeDir: string,
  scope: MemoryScope,
  project_id: string | undefined,
  format: ImportFormat,
  options: ImportOptions
): ImportResult {
  const started = Date.now();
  const plan = planImport(service, exportScopeDir, scope, project_id, format, options);
  const apply = applyImport(service, plan, options);
  return {
    applied:
      options.dry_run
        ? false
        : apply.errors.length === 0 &&
          (apply.applied > 0 || (plan.inserts.length === 0 && plan.replacements.length === 0)),
    plan,
    duration_ms: Date.now() - started,
    applied_ids: apply.applied_ids,
    import_batch_id: plan.import_batch_id
  };
}
